### ISSUE TITLE
Morning review

### ISSUE THREAD

**Issue by nyatindopatrick** [Eshy10/HTML-FORMS#6]

**Comment by Kyle-Law** [comment]
Review by Patrick classmate - Kyle:
1) For the header part, try to avoid over-reliant on margins, they are the culprits of why your website is not responsive. Instead, either use `display: flex` combined with `justify-content: center` to centralize along the horizontal axis, or `display: grid` with `justify-content: center`.
2) Good idea for using `float: right` to align `.sign-in`
3) Good idea using `margin:0 auto;` and `text-align: center` to centralize the form part.
4) Interesting to see how you incorporate the locker icon inside password input by using `margin-left: -1.5rem;` and `opacity: 0.3;`

**Comment by patriciachrysy** [comment]
Nice code, I will just give some best practice advice:
- give more attribute to your form tags (method, action)
- give a name attribute to your inputs
- put your footer menu into a nav instead of a list
- try to use more selector and fewer classes
- user border property on your button to avoid the default browser style to apply on it
- often use icons than images, they are easier to style
- To center any div, use these three properties: `{display: block; margin: auto; width: 40px}`
The result is nice, good job

**Comment by dili021** [comment]
Everything is well done, these are just some minor readability suggestions:
-collect project images and style.css file into an assets folder
-add descriptive comments so it's easier to distinguish sections of the code
-most of the image alt attributes are empty
-move closing tag from line 30 back to line 29
-whenever able you should use class instead of id, used here for password, phone and email
